/* DO NOT REMOVE COMMENT - GEN INCLUDE SECTION */
#include "GEN_LCD_Driver_SERVER_PORTS_CFG.h"
#include "GEN_LCD_Driver_CLIENT_PORTS_CFG.h"
#include "LCD_Driver.h"
/* DO NOT REMOVE COMMENT - GEN END SECTION */

/* DO NOT REMOVE COMMENT - GEN SERVER PORTS-VARS SECTION */
/* DO NOT REMOVE COMMENT - GEN END SECTION */

/* DO NOT REMOVE COMMENT - GEN SERVER PORTS-FUNCS SECTION */
/* DO NOT REMOVE COMMENT - GEN START FUNC */
Func_ReturnType LCD_Driver_LCD_Begin()
{

}
/* DO NOT REMOVE COMMENT - GEN END FUNC */

/* DO NOT REMOVE COMMENT - GEN START FUNC */
Func_ReturnType LCD_Driver_LCD_Clear()
{

}
/* DO NOT REMOVE COMMENT - GEN END FUNC */

/* DO NOT REMOVE COMMENT - GEN START FUNC */
Func_ReturnType LCD_Driver_LCD_SetCursor(uint8 line, uint8 pos)
{

}
/* DO NOT REMOVE COMMENT - GEN END FUNC */

/* DO NOT REMOVE COMMENT - GEN START FUNC */
Func_ReturnType LCD_Driver_LCD_WriteString(uint8* data, uint8 data_length)
{

}
/* DO NOT REMOVE COMMENT - GEN END FUNC */

/* DO NOT REMOVE COMMENT - GEN START FUNC */
Func_ReturnType LCD_Driver_LCD_WriteNumber(sint32 num)
{

}
/* DO NOT REMOVE COMMENT - GEN END FUNC */
/* DO NOT REMOVE COMMENT - GEN END SECTION */

/* DO NOT REMOVE COMMENT - GEN RUNNABLES SECTION */
/* DO NOT REMOVE COMMENT - GEN END SECTION */