/* DO NOT REMOVE COMMENT - GEN INCLUDE SECTION */
#include "GEN_CompLedIndicator_SERVER_PORTS_CFG.h"
#include "GEN_CompLedIndicator_CLIENT_PORTS_CFG.h"
#include "CompLedIndicator.h"
/* DO NOT REMOVE COMMENT - GEN END SECTION */

/* DO NOT REMOVE COMMENT - GEN SERVER PORTS-VARS SECTION */
/* DO NOT REMOVE COMMENT - GEN END SECTION */

/* DO NOT REMOVE COMMENT - GEN SERVER PORTS-FUNCS SECTION */
/* DO NOT REMOVE COMMENT - GEN END SECTION */

/* DO NOT REMOVE COMMENT - GEN RUNNABLES SECTION */
/* DO NOT REMOVE COMMENT - GEN START FUNC */
void CompLedIndicator_Init(void)
{

}
/* DO NOT REMOVE COMMENT - GEN END FUNC */

/* DO NOT REMOVE COMMENT - GEN START FUNC */
void CompLedIndicator_Cyclic(void)
{

}
/* DO NOT REMOVE COMMENT - GEN END FUNC */
/* DO NOT REMOVE COMMENT - GEN END SECTION */